{{- if .Values.userDb.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "archiva.fullname" . }}
  labels:
    app: {{ template "archiva.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  db-password: {{ .Values.userDb.password | b64enc | quote }}
{{- end }}
